### ISSUE TITLE
NXspecdata checklist

### ISSUE THREAD

**Issue by prjemian** [nexusformat/definitions#483]
from #477 
- [x] NXuser: 510b2b25ba345a33e9b3d3c1296c903e355e283d
- [x] NXmonitor: 243de8d2292ae143689a15158581d7c6275cb7ab
- [x] intensity_factor:     892873e
- [ ] NXdata documentation about how scan data is to be stored
- [ ] documentation for counter_cross_reference
- [ ] documentation for positioners_cross_reference
- [ ] documentation for the G group
- [ ] documentation for the positions group 
- [ ] documentation for other NXnote groups
- [x] certain attributes in the root class should be optional:  3efce81857487b41c7b4b01663cd8c761f57ef61
- [ ] the MCA group (now an NXnote) could be an NXdetector
- [ ] can the positioners fit into NXpositioner
- [ ] clarify what items are defined from SPEC macros
- [ ] clarify what items appear on a conditional basis

**Comment by zjttoefs** [comment]
I have lost track of what this list means. Looks half documentation tasks, half research, and some discussion items. 
This is pre-proposal and all contained to NXspecdata, right?

**Comment by prjemian** [comment]
For reference on the research aspect, see https://github.com/prjemian/spec2nexus/issues/51 and https://github.com/prjemian/spec2nexus/pull/187, then mostly documentation.  Always room for more discussion, but that can wait for now.

**Comment by prjemian** [comment]
For the documentation, to keep the NeXus specification brief, reference will be made to the [specnexus](https://github.com/prjemian/spec2nexus) documentation, which will be made to satisfy the check list above.

**Comment by prjemian** [comment]
I am willing to discard this contributed definition.  If no interest, I will discard with assigned milestone.

**Comment by vasole** [comment]
I have no objection to discard the definition.

Just for information, ESRF just makes SPEC files look as if they would have been acquired following our new acquisition system but without actually converting them. The actual conversion had a reason of being during the transition period. Particularly because of the 1 year shutdown.

**Comment by prjemian** [comment]
I will notify the NeXus mailing list of this intent.

**Comment by prjemian** [comment]
closing per #856
